pipeline:
  name: pipeline
  identifier: pipeline
  projectIdentifier: fullstack_githu
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: new_crud
        repoName: django-crud
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo 'success'
              - step:
                  type: Run
                  name: Run Tests
                  identifier: run_tests
                  spec:
                    connectorRef: account.harnessImage
                    image: python:3.9
                    shell: Sh
                    command: |
                      pip install -r requirements.txt
                      python manage.py test blog
              - step:
                  type: Run
                  name: push to prod
                  identifier: push_to_prod
                  spec:
                    shell: Sh
                    command: |-
                      git config --global user.email "jha.abhishek001@gmail.com"
                      git config --global user.name "jha713"
                      git fetch --all && git checkout prod  &&
                              git merge origin/dev &&
                              git push https://<+secrets.getValue("GIT_USERNAME")>:<+secrets.getValue("GIT_PASSWORD")>@github.com/jha713/django-crud.git prod ||
                              echo "Error: Failed to move changes to prod branch"
